### ISSUE TITLE
pydantic instrument-type required field missing error

### ISSUE THREAD

**Issue by pressplay21** [tastyware/tastytrade#91] opened 2023-09-26 23:55 UTC
**Describe the bug**
I'm using Option object to build a leg but it's causing a pydantic error. I think somehow the attributes from Option  are not inherited.

ValidationError: 1 validation error for Leg
instrument-type
  Field required [type=missing, input_value={'instrument_type': <Inst...O_OPEN: 'Sell to Open'>}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing

**How to reproduce**
1. Create a TT session
```
from tastytrade import CertificationSession
from tastytrade import ProductionSession
from tastytrade import DataStreamer
from tastytrade.dxfeed.event import EventType
from tastytrade.instruments import get_option_chain
from tastytrade.order import NewOrder, OrderAction, OrderTimeInForce, OrderType, PriceEffect, Leg, InstrumentType


session = ProductionSession(username,password,remember_me=True)
session = ProductionSession(username,remember_token=session.remember_token)
```

2. Setup the symbol and get the chain. Change the expiration date as needed
```
symbol = 'SPXW'
chain = get_option_chain(session,symbol)
expiration_date = date(2023,9,29)

```
3. The object has the instrument_type but when you try to build a leg, it doesn't work.
```
chain[expiration_date][0]
chain[expiration_date][0].build_leg(Decimal(1),OrderAction.SELL_TO_OPEN)
```

4. This one should easily return a Leg option but fails with instrument-type missing error.
```
leg = {
    'quantity': Decimal('1'),
    'action': OrderAction.SELL_TO_CLOSE,
    'symbol': '.SPXW230926C1200',
    'instrument_type': InstrumentType.EQUITY_OPTION
}

from tastytrade.order import  Leg

Leg(**leg)

```

**Comment by Graeme22** [comment] 2023-10-24 16:48
I'm unable to reproduce :(

Could you check your pydantic version?

**Comment by Mytak** [comment] 2023-10-25 15:14
I have a similar error and do not know if it is related to this bug: 
"MarketMetricInfo(**entry) for entry in data]
 File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 7 validation errors for MarketMetricInfo
implied-volatility-index
field required (type=value_error.missing)
implied-volatility-index-5-day-change
field required (type=value_error.missing)
tos-implied-volatility-index-rank  
field required (type=value_error.missing)
tw-implied-volatility-index-rank
field required (type=value_error.missing)
implied-volatility-updated-at
field required (type=value_error.missing)
liquidity-rating
field required (type=value_error.missing)
option-expiration-implied-volatilities
field required (type=value_error.missing)'" 

but found a workaround by making the above metrics optional -> see attached metrics.py
[metrics.zip](https://github.com/tastyware/tastytrade/files/13167631/metrics.zip)

**Comment by Graeme22** [comment] 2023-10-25 16:15
> I have a similar error which may be related to this issue:

This is unrelated, but the good news is your issue is already fixed in the main branch, and will be in the next release.

**Comment by Graeme22** [comment] 2023-12-28 22:35
Closing as stale

**Closed by Graeme22** 2023-12-28 22:35 UTC
