### ISSUE TITLE
day_trader_status is bool, not str

### ISSUE THREAD

**Issue by Quenos** [tastyware/tastytrade#58] opened 2023-07-01 12:34 UTC
account.py {373}

```
class Account(TastytradeJsonDataclass):

...
day_trader_status: str
...
```

Should be changed to:

```
...
day_trader_status: bool
...
```

**Comment by Graeme22** [comment] 2023-07-02 18:53
Interesting, that's not very intuitive... Does that mean you're flagged as a PDT?

Could you provide the output when you create an account?

**Comment by Quenos** [comment] 2023-07-02 20:28
![Screenshot 2023-07-02 at 22 27 36](https://github.com/tastyware/tastytrade/assets/34926461/c9802a78-30ed-4302-84ca-2795f14c5601)
![Screenshot 2023-07-02 at 22 27 11](https://github.com/tastyware/tastytrade/assets/34926461/cb823026-897e-4913-844d-0bac74150d56)
![Screenshot 2023-07-02 at 22 27 00](https://github.com/tastyware/tastytrade/assets/34926461/e0e92e30-32fd-4e89-a785-a77115f5770c)

**Comment by Graeme22** [comment] 2023-07-02 21:13
![Screenshot_20230702-161107~2.png](https://github.com/tastyware/tastytrade/assets/4185684/ddca2e67-e55f-40a5-98a4-0ae889d51724)

According to the official docs it's a string... Could you see what happens if you place a day trade? I'd need to see that, as well as the output for an account >$25k to be sure it's always a bool.

**Comment by Quenos** [comment] 2023-07-03 13:56
the issue has been resolved. After I ran into a lot of other issues, I realised that not all dependencies had been properly installed.
After installing them everything seems to be ok.

**Comment by Graeme22** [comment] 2023-07-04 16:44
Great!

**Comment by pressplay21** [comment] 2023-10-18 04:43
@Quenos How did you get it resolved? Tastytrade returns day_trader_status = False (which is a bool).
Pydantic TastytradeJsonDataclass rejects it because day_trader_status is set to str.  I can change it to bool but I'm not sure how it's working for others.

@Graeme22 FYI . I'm not sure how it's working for you. I can just directly load this class and test it manually and it failed bool vs str. See your Account class below.

class Account(TastytradeJsonDataclass):
    """
    Dataclass that represents a Tastytrade account object, containing
    methods for retrieving information about the account, placing orders,
    and retrieving past transactions.
    """
    account_number: str
    opened_at: datetime
    nickname: str
    account_type_name: str
    is_closed: bool
    day_trader_status: str
    is_firm_error: bool
    is_firm_proprietary: bool
    is_futures_approved: bool
    is_test_drive: bool
    margin_or_cash: str
    is_foreign: bool
    created_at: datetime
    external_id: Optional[str] = None
    closed_at: Optional[str] = None
    funding_date: Optional[date] = None
    investment_objective: Optional[str] = None
    liquidity_needs: Optional[str] = None
    risk_tolerance: Optional[str] = None
    investment_time_horizon: Optional[str] = None
    futures_account_purpose: Optional[str] = None
    external_fdid: Optional[str] = None
    suitable_options_level: Optional[str] = None
    submitting_user_id: Optional[str] = None

    @classmethod
    def get_accounts(
        cls,
        session: Session,
        include_closed=False
    ) -> List['Account']:
        """
        Gets all trading accounts from the Tastyworks platform. By default
        excludes closed accounts from the results.

        :param session: the session to use for the request.

        :return: a list of :class:`Account` objects.
        """

        response = requests.get(
            f'{session.base_url}/customers/me/accounts',
            headers=session.headers
        )
        validate_response(response)  # throws exception if not 200

        accounts = []
        data = response.json()['data']['items']
        for entry in data:
            account = entry['account']
            if not include_closed and account['is-closed']:
                continue
            accounts.append(cls(**account))

        return accounts

**Comment by Graeme22** [comment] 2023-10-25 16:07
Hmm, could you post the output of `pip list`?

**Comment by Graeme22** [comment] 2023-10-25 16:09
According to the docs it's still a string

**Comment by Quenos** [comment] 2023-11-18 09:53
And here it's still working.
As you can read from the thread, I installed requirements.txt
That did it for me.

**Comment by Graeme22** [comment] 2023-11-25 02:35
I'm going to close this unless I hear further comments. I believe the problem is related to using pydantic 2 instead of 1, which breaks the type validation.

**Closed** 2023-11-25 02:35 UTC
